Sprint 8 solution time and duration
DmitryFedoroff/java-kanban pull request #45
Opened 2024-07-13 22:05 UTC by DmitryFedoroff

#comment Refactor task management system and testing suite:

1. Introduce BaseTask, SimpleTask, EpicTask, and Subtask classes with properties such as ID, title, description, status, duration, and start time.
2. Implement InMemoryTaskManager and FileBackedTaskManager to handle tasks in memory and with file persistence respectively.
3. Develop EpicTask handling, including adding and removing subtasks, and automatic status updates based on subtask statuses.
4. Create HistoryManager and InMemoryHistoryManager to track recently viewed tasks.
5. Add task overlapping validation to ensure no two tasks overlap in time.
6. Extend task management features to include getting prioritized tasks by start time.
7. Write comprehensive unit tests for BaseTask, SimpleTask, EpicTask, Subtask, InMemoryTaskManager, FileBackedTaskManager, and InMemoryHistoryManager.
8. Refactor Main class to demonstrate task creation, updating, deletion, and viewing history.
9. Include ManagerSaveException for handling file persistence errors gracefully.

Affected: tasks.csv, Main, FileBackedTaskManager, InMemoryHistoryManager, InMemoryTaskManager, TaskManager, BaseTask, EpicTask, SimpleTask, Subtask, FileBackedTaskManagerTest, InMemoryHistoryManagerTest, InMemoryTaskManagerTest, TaskManagerTest, EpicTaskTest

2024-07-15 13:28 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-15 13:28 UTC, LexLippi commented on src/taskmanagement/manager/InMemoryTaskManager.java
> +    public List<BaseTask> getPrioritizedTasks() {
Этот метод должен быть задекларирован в интерфейсе, а значит должна быть аннотация `@Override`

2024-07-15 13:28 UTC, LexLippi commented on src/taskmanagement/manager/InMemoryTaskManager.java
> +                .filter(existingTask -> existingTask.getId() != task.getId())
Лучше не делать заранее `filter`, а добавить это условие в `anyMatch`, потому что иначе мы пробежимся по коллекции дважды, чего нам бы не хотелось

2024-07-15 13:28 UTC, LexLippi commented on src/taskmanagement/manager/InMemoryTaskManager.java
> +    }
Вот такой метод точно не стоит декларировать в интерфейсе, так как мы не хотим показывать, что у нас внутри есть какой-то менеджер, у нас есть история просмотра, к которой пользователи нашего менеджера имеют доступ, а уж как она у нас реализована им доступно быть не должно

2024-07-15 13:28 UTC, LexLippi commented on src/taskmanagement/task/BaseTask.java
> +    }
Кажется, что стоит завести класс `TimeUtils` в котором есть один статический метод `timeToString`, он принимает `LocalDateTime` и вычисляет ровно то, что ты делаешь, тогда мы сможем избавиться от дублирования кода

2024-07-15 13:28 UTC, LexLippi commented on src/taskmanagement/task/BaseTask.java
> +        if (this.startTime == null || other.getStartTime() == null) {
Вот эти строки можно добавить в итоговое условие, так как в java ленивые логические операнды и если они знают результат операции, после выполнения одного условия они не будут выполнять следующие операции

2024-07-15 16:02 UTC, DmitryFedoroff commented on src/taskmanagement/manager/InMemoryTaskManager.java
> +    public List<BaseTask> getPrioritizedTasks() {
__Исправлено__: Метод `getPrioritizedTasks`получил аннотацию `@Override` в классе `InMemoryTaskManager`.

2024-07-15 16:03 UTC, DmitryFedoroff commented on src/taskmanagement/manager/InMemoryTaskManager.java
> +                .filter(existingTask -> existingTask.getId() != task.getId())
__Исправлено__: Метод `isTaskOverlapping` оптимизирован, чтобы использовать условие внутри `anyMatch` для повышения эффективности.

2024-07-15 16:05 UTC, DmitryFedoroff commented on src/taskmanagement/manager/InMemoryTaskManager.java
> +    }
__Исправлено__: Метод `getHistoryManager` исключен из интерфейса `TaskManager`, чтобы скрыть реализацию истории задач.

2024-07-15 16:07 UTC, DmitryFedoroff commented on src/taskmanagement/task/BaseTask.java
> +    }
__Исправлено__: Методы `getStartTimeToString` и `getEndTimeToString` в классе `BaseTask` теперь используют утилитарный метод `timeToString` из нового класса `TimeUtils` в пакете `util` для устранения дублирования кода.

2024-07-15 16:10 UTC, DmitryFedoroff commented on src/taskmanagement/task/BaseTask.java
> +        if (this.startTime == null || other.getStartTime() == null) {
__Исправлено__: Условие в методе `isOverlapping` упрощено с использованием ленивых логических операндов.

2024-07-16 10:23 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-07-16 15:29 UTC, merged