Sprint 9 solution http api
DmitryFedoroff/java-kanban pull request #46
Opened 2024-07-26 19:16 UTC by DmitryFedoroff

#comment Refactor task management system to include HTTP server and request handlers, create new adapters for LocalDateTime and Duration serialization, and enhance unit test coverage:

1. Introduce HttpTaskServer to handle HTTP requests for task management.
2. Define BaseHttpHandler as an abstract base class for all HTTP handlers.
3. Implement EpicsHandler, HistoryHandler, PrioritizedHandler, SubtasksHandler, and TasksHandler for handling respective HTTP requests.
4. Create NotFoundException for handling resource not found errors.
5. Implement LocalDateTimeAdapter for LocalDateTime serialization and deserialization.
6. Add DurationAdapter for Duration serialization and deserialization.
7. Refactor TaskManager to support new HTTP server and handlers.
8. Enhance SimpleTask class to support new features.
9. Improve TimeUtils methods for better date-time handling.
10. Develop unit tests for HttpTaskServer and its handlers.
11. Add unit tests for LocalDateTimeAdapter and DurationAdapter.
12. Update SimpleTaskTest to cover changes in SimpleTask.

Affected: HttpTaskServer, BaseHttpHandler, EpicsHandler, HistoryHandler, PrioritizedHandler, SubtasksHandler, TasksHandler, NotFoundException, LocalDateTimeAdapter, DurationAdapter, TaskManager, SimpleTask, TimeUtils, HttpTaskManagerTasksTest, HttpTaskManagerSubtasksTest, HttpTaskManagerPrioritizedTest, HttpTaskManagerHistoryTest, HttpTaskManagerEpicsTest, DurationAdapterTest, LocalDateTimeAdapterTest, SimpleTaskTest"

2024-07-27 11:06 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара небольших замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-27 11:06 UTC, LexLippi commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +            if (epicId.isPresent()) {
Для такого стоит использовать функционал `.ifPresentOrElse()`

2024-07-27 11:06 UTC, LexLippi commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +            if (epic.getId() != 0) {
В таком случае лучше использовать не примитивный тип `int`, а объектный тип `Integer` и в таком случае сделать проверку на `null`

2024-07-27 11:06 UTC, LexLippi commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +        if (epicId.isPresent()) {
Аналогично стоит использовать `.ifPresentOrElse()`

2024-07-27 11:06 UTC, LexLippi commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +        if (epicId.isPresent()) {
Про это уже писал

2024-07-27 11:06 UTC, LexLippi commented on src/taskmanagement/http/handlers/SubtasksHandler.java
> +            if (subtask.getId() != 0) {
про это уже писал

2024-07-27 11:06 UTC, LexLippi commented on src/taskmanagement/http/handlers/TasksHandler.java
> +            if (task.getId() != 0) {
Про это уже писал

2024-07-28 12:17 UTC, DmitryFedoroff commented on src/taskmanagement/util/TimeUtils.java
> +        return LocalDateTime.parse(time, DATE_TIME_FORMATTER);
**Исправлено**: Использован тернарный оператор для проверки на `null` в методе stringToTime.

2024-07-28 12:20 UTC, DmitryFedoroff commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +            if (epicId.isPresent()) {
**Исправлено**: Устранена проверка `.isPresent`, заменена на использование `.ifPresentOrElse` для получения `epicId`.

2024-07-28 12:23 UTC, DmitryFedoroff commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +            if (epic.getId() != 0) {
**Исправлено**: Использован тип `Integer` вместо типа `int` для `ID` с проверкой на `null`.

2024-07-28 12:27 UTC, DmitryFedoroff commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +        if (epicId.isPresent()) {
**Исправлено**: Устранена проверка `.isPresent()`, заменена на использование `.ifPresentOrElse()` для `handleGetEpicById()`.

2024-07-28 12:29 UTC, DmitryFedoroff commented on src/taskmanagement/http/handlers/EpicsHandler.java
> +        if (epicId.isPresent()) {
**Исправлено**: Устранена проверка `.isPresent()`, заменена на использование `.ifPresentOrElse() для `handleDeleteEpicById()`.

2024-07-28 12:31 UTC, DmitryFedoroff commented on src/taskmanagement/http/handlers/SubtasksHandler.java
> +            if (subtask.getId() != 0) {
**Исправлено**: Использован тип `Integer` вместо типа `int` для `ID` с проверкой на `null`.

2024-07-28 12:31 UTC, DmitryFedoroff commented on src/taskmanagement/http/handlers/TasksHandler.java
> +            if (task.getId() != 0) {
***Исправлено*: Использован тип `Integer` вместо типа `int` для `ID` с проверкой на `null`.

2024-07-29 07:16 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-07-31 13:52 UTC, merged